# 예외 처리

## 1. 예외 클래스

### 1) 오류란?
1. 컴파일 오류: 프로그램 코드 작성 중 실수로 발생하는 것
2. 실행 오류: 실행 중인 프로드램이 의도하지 않은 동작을 하거나 프로그램이 중지되는 경우
    * 시스템 오류: 프로그램에서 제어할 수 없는 오류(동적 메모리 부족 등..)
    * 예외: 프로그램에서 제어할 수 있는 오류(파일이 없는 경우, 네트워크 연결이 안된 경우..)

<br>

### 2) 예외 클래스
예외 클래스의 최상위 클래스는 Excption 클래스이다. Exception 클래스의 하위 클래스에는 정말 다양한 예외 처리 클래스들이 존재한다.
<img src="https://cdn.programiz.com/sites/tutorial2program/files/ExceptionHierarchy.png"> </img>

<br>

## 2. 예외 처리하기
### 1)try-catch문

try-catch문은 예외를 처리하는데 가장 기본적인 문법이다. try 블록에는 예외가 발생할 가능성이 있는 코드를 작성한다. 만약 try 블록 안에서 예외가 발생하면 바로 catch 블록이 수행된다.

try-catch문 사용하기 [배열 개수가 범위를 벗어난 경우]
```java
package exception;

public class ArrayExceptionHandling {
	public static void main(String[] args) {
		int[] arr= new int[5];
		
		try {
			for(int i=0; i<=5; i++) {  //arr[4]까지 존재하므로 i가 5가 되는 순간 예외가 발생함
				arr[i]=i;
				System.out.println(arr[i]);
			  }
			}
		catch(ArrayIndexOutOfBoundsException e){  //배열 개수가 범위를 벗어난 경우 사용하는 클래스: ArrayIndexOutOfBoundsException
			System.out.println(e);  //e.toString이 출력됨
			System.out.println("예외 처리 부분");  //예외가 발생하면 수행됨
		}
		
		System.out.println("프로그램 종료");
		
  }
}
```

#### 실행 결과
0        
1             
2                   
3               
4        
java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 5   
예외 처리 부분  
프로그램 종료              

 <br>   

### 2)try-catch-finally문  
finally 문은 일단 try 블록이 실행되었을 때 그 다음 무조건 실행되어야 하는 코드가 작성된다. 이를테면 try나 catch문에 return 문이 있어도 수행된다.

try-catch-finally문 사용하기 [열고자하는 파일이 없는 경우]
```java
package exception;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;

public class ArrayExceptionHandling2 {
	public static void main(String[] args) {
		
		FileInputStream fis =null;  
		
		try {
			fis = new FileInputStream("a.txt");  //a.txt 파일 열기
		}catch(FileNotFoundException e){   //열 파일이 없다면
			System.out.println(e);  //오류 구문 출력
			return;    //여기서 return해도 finally구문이 실행되기 전 까지는 종료되지 않음
		}finally {
			if(fis!=null) {    
			 try {
				 fis.close();  //파일 닫기
			 }catch(IOException e) {    //닫을 파일이 없다면
				 e.printStackTrace();  //오류 구문 출력
			   }
			}
			System.out.println("항상 수행 됩니다.");  //finally문 안에 들어있기 때문에 항상 수행된다.
		}
		System.out.println("여기도 수행됩니다.");  //예외 처리를 하여 프로그램이 정상적으로 정료되었기 때문에 수행된다.
	}
}
```

<br>

### 3) try-with-resources문
앞에서 사용한 코드는 다속 복잡하다. 자바 7부터는 try-with-resources문을 제공하여 close() 메서드를 명시적으로 호출하지 않아도 try 블록 내에서 열린 리소드를 자동으로 닫도록 만들 수 있다. AutoCloseable 인터페이스에는 close()가 구현되어 있어, 이를 구현한 클래스는 close()를 호출하지 않아도 된다. 앞서 사용한 FileInPutStream에는 AutoCloseable 인터페이스가 구현되어 있다.

<br>

AutoCloseable 인터페이스 구현한 클래스 만들기
```java
package exception;

public class AutoCloseObj implements AutoCloseable{

	@Override
	public void close() throws Exception {
		System.out.println("리소스가 close() 되었습니다.");
		
	}

}

```

<br>

try-with-resources문 사용하기1
```java
package exception;

public class AutoCloseTest {
	public static void main(String[] args) {
		try(AutoCloseObj obj = new AutoCloseObj()){ //try의 괄호안에 사용할 리서스를 넣어줘야 한다.
		}catch(Exception e) {
			System.out.println("예외 부분입니다.");
		}
	}
}
```

#### 실행 결과
실행 결과 AutoCloseObj클래스의 close 메서드가 실행되어 "리소스가 close() 되었습니다."가 출력된다.

<br>

try-with-resources문 사용하기2 (강제로 예외 발생시키기)    
throw new Exception() 문자을 사용하면 프로그램에서 강제로 예외를 발생시켜 catch 블록이 수행된다.
```java
package exception;

public class AutoCloseTest {
	public static void main(String[] args) {
		try(AutoCloseObj obj = new AutoCloseObj()){ //사용할 리소스는 try 구문 안에서 선언해 주어야 한다.
			throw new Exception();
		}catch(Exception e) {
			System.out.println("예외 부분입니다.");
		}
	}
}


```
#### 실행 결과
리소스가 close() 되었습니다.              
예외 부분입니다.   

출력 결과 리소스의 close() 메서드가 실행되고, catch 블록이 실행된다.
                 
<br>

## 3. 예외 처리 미루기
예외 처리를 하는 방법은 2가지가 있는데, 첫 번째는 앞서 본 try-catch문이고, 두번 째는 throws로 예외를 미루는 것이다. throws를 사용하면 예외를 해당 메서드에서 처리하지 않고 미룬 후 메서드를 호출하여 사용하는 부분에서 예외를 처리한다.

throws로 예외 미루기
```java
package exception;

import java.io.FileInputStream;
import java.io.FileNotFoundException;

public class ThrowsException {

	public Class loadClass(String fileName, String className) throws FileNotFoundException, ClassNotFoundException{  //두 예외를 메서드가 호출될 떄 처리하도록 미룸
		FileInputStream fis = new FileInputStream(fileName); //FileNotFoundException 
		Class c = Class.forName(className);  //ClassNotFoundException 
		return c;
	}

	public static void main(String[] args) {

		ThrowsException test = new ThrowsException();  
		
		try {
			test.loadClass("a.txt", "java.lang.String");  //메서드가 사용될 때 처리
		
		}catch (FileNotFoundException e) {    //열 파일이 없을 때
			e.printStackTrace();
		} catch (ClassNotFoundException e) {    //열 클래스가 없을 때
			e.printStackTrace();
		}catch (Exception e) {    //어떤 예외가 발생할 지 알수 없는 경우
			e.printStackTrace();
		}
	}
}
```

<br>

#### 다중 예외 처리
바로 위에서 작성한 것 처럼 어떤 예외가 발생할 지 알수 없는 경우에는 Exception 클래스를 사용하는데,  Exception 클래스는 모든 예외 클래스의 최상위 클래스이기 때문에, 다중 예외 처리를 할 경우 맨 아래 작성해야 한다. 다른 예외 클래스보다 위에 작성할 경우, 모든 예외가 Exception 클래스로 수행되기 때문에 그 아래 줄에 사용되는 예외 클래스들은 쓸모가 없어진다.

<br>

### 4) 사용자 정의 예외
자바에서 제공하는 예외 처리 클래스 이외에 예외 처리 상황이 필요한 경우, 예외 클래스를 직접 정의해서 사용하면된다. 구현 시에는 기존 JDK에서 제공하는 예외 클래스 중 가장 유사한 클래스를 상속받는 것이 좋은데, 유사한 예외 클래스를 잘 모르겠다면 가장 상위 클래스인 Exception을 상속받으면 된다.

<br>

사용자 정의 예외 구현하기
```java
package exception;

public class IDFormatException extends Exception{
	public IDFormatException(String message) {
		super(message);  //Exception 클래스에서 메시지 생성자, 멤버 변수와 메서드를 이미 제공하고 있으므로, 부모클래스의 생성자에 message를전달
	}
}

```

<br>

사용자 정의 예외 테스트하기      
ID를 입력하지 않았거나, 8자 이상 20자 이하로 쓰지 않았을 때 예외 발생
```java
package exception;

public class IDFormatTest {
	
	private String userID;

	public String getUserID() {
		return userID;
	}

	public void setUserID(String userID) throws IDFormatException {  //IDFormatException 예외를 setUserID() 메서드가 호출될 때 까지 미루기
		if(userID == null) {    
			throw new IDFormatException("아이디는 null일 수 없습니다.");   //강제로 얘외 발생시킴
		}
		else if(userID.length()<8||userID.length()>20) {
			throw new IDFormatException("아이디는 8자 이상 20자 이하로 쓰세요");   //강제로 예외 발생시킴
		}
		
		this.userID = userID;
	}
	
	public static void main(String[] args) {
		
		IDFormatTest test = new IDFormatTest();
		
		// ID가 null인 경우
		String userID = null;
		try {
			test.setUserID(userID);
		}catch(IDFormatException e){
			System.out.println(e.getMessage());
		}
		
		//ID가 8자 이하인 경우
	    userID = "1234";
		try {
			test.setUserID(userID);
		}catch(IDFormatException e){
			System.out.println(e.getMessage());
		}
	}
```


